In [1]:
## Standard Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
## Importing the OS and JSON Modules
import os,json

In [2]:
super_info_df = pd.read_csv("/Users/Rashad/Documents/GitHub/Applying Advanced Transformations_CORE/Superhero-Transformations/Data/superhero_info.csv")
super_info_df

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"
...,...,...,...,...,...,...,...,...
458,Yellowjacket|Marvel Comics,Male,Human,good,Blond,blue,Unknown,"{'Height': '183.0 cm', 'Weight': '83.0 kg'}"
459,Yellowjacket II|Marvel Comics,Female,Human,good,Strawberry Blond,blue,Unknown,"{'Height': '165.0 cm', 'Weight': '52.0 kg'}"
460,Yoda|George Lucas,Male,Yoda's species,good,White,brown,green,"{'Height': '66.0 cm', 'Weight': '17.0 kg'}"
461,Zatanna|DC Comics,Female,Human,good,Black,blue,Unknown,"{'Height': '170.0 cm', 'Weight': '57.0 kg'}"
462,Zoom|DC Comics,Male,Unknown,bad,Brown,red,Unknown,"{'Height': '185.0 cm', 'Weight': '81.0 kg'}"

In [3]:
super_powers_df = pd.read_csv("/Users/Rashad/Documents/GitHub/Applying Advanced Transformations_CORE/Superhero-Transformations/Data/superhero_powers.csv")
super_powers_df

          hero_names                                             Powers
0            3-D Man         Agility,Super Strength,Stamina,Super Speed
1             A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2         Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3           Abin Sur                                 Lantern Power Ring
4        Abomination  Accelerated Healing,Intelligence,Super Strengt...
..               ...                                                ...
662  Yellowjacket II                 Flight,Energy Blasts,Size Changing
663             Ymir  Cold Resistance,Durability,Longevity,Super Str...
664             Yoda  Agility,Stealth,Danger Sense,Marksmanship,Weap...
665          Zatanna  Cryokinesis,Telepathy,Magic,Fire Control,Proba...
666             Zoom  Super Speed,Intangibility,Time Travel,Time Man...

[667 rows x 2 columns]

In [4]:
super_info_df['Hero|Publisher']

0               A-Bomb|Marvel Comics
1       Abe Sapien|Dark Horse Comics
2                 Abin Sur|DC Comics
3          Abomination|Marvel Comics
4        Absorbing Man|Marvel Comics
                   ...
458       Yellowjacket|Marvel Comics
459    Yellowjacket II|Marvel Comics
460                Yoda|George Lucas
461                Zatanna|DC Comics
462                   Zoom|DC Comics
Name: Hero|Publisher, Length: 463, dtype: object

In [5]:
## save the 2 new columns into the dataframe
#df[['area_code','phone_number']] = df['display_phone'].str.split(' ',expand=True)
#df.head(2)

super_info_df[['Hero','Publisher']] = super_info_df['Hero|Publisher'].str.split('|',expand=True)

In [6]:
super_info_df

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics
...,...,...,...,...,...,...,...,...,...,...
458,Yellowjacket|Marvel Comics,Male,Human,good,Blond,blue,Unknown,"{'Height': '183.0 cm', 'Weight': '83.0 kg'}",Yellowjacket,Marvel Comics
459,Yellowjacket II|Marvel Comics,Female,Human,good,Strawberry Blond,blue,Unknown,"{'Height': '165.0 cm', 'Weight': '52.0 kg'}",Yellowjacket II,Marvel Comics
460,Yoda|George Lucas,Male,Yoda's species,good,White,brown,green,"{'Height': '66.0 cm', 'Weight': '17.0 kg'}",Yoda,George Lucas
461,Zatanna|DC Comics,Female,Human,good,Black,blue,Unknown,"{'Height': '170.0 cm', 'Weight': '57.0 kg'}",Zatanna,DC Comics
462,Zoom|DC Comics,Male,Unknown,bad,Brown,red,Unknown,"{'Height': '185.0 cm', 'Weight': '81.0 kg'}",Zoom,DC Comics

In [7]:
## drop the original column 
super_info_df = super_info_df.drop(columns='Hero|Publisher')

In [8]:
super_info_df

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics
...,...,...,...,...,...,...,...,...,...
458,Male,Human,good,Blond,blue,Unknown,"{'Height': '183.0 cm', 'Weight': '83.0 kg'}",Yellowjacket,Marvel Comics
459,Female,Human,good,Strawberry Blond,blue,Unknown,"{'Height': '165.0 cm', 'Weight': '52.0 kg'}",Yellowjacket II,Marvel Comics
460,Male,Yoda's species,good,White,brown,green,"{'Height': '66.0 cm', 'Weight': '17.0 kg'}",Yoda,George Lucas
461,Female,Human,good,Black,blue,Unknown,"{'Height': '170.0 cm', 'Weight': '57.0 kg'}",Zatanna,DC Comics
462,Male,Unknown,bad,Brown,red,Unknown,"{'Height': '185.0 cm', 'Weight': '81.0 kg'}",Zoom,DC Comics

In [9]:
super_info_df['Measurements']

0      {'Height': '203.0 cm', 'Weight': '441.0 kg'}
1       {'Height': '191.0 cm', 'Weight': '65.0 kg'}
2       {'Height': '185.0 cm', 'Weight': '90.0 kg'}
3      {'Height': '203.0 cm', 'Weight': '441.0 kg'}
4      {'Height': '193.0 cm', 'Weight': '122.0 kg'}
                           ...
458     {'Height': '183.0 cm', 'Weight': '83.0 kg'}
459     {'Height': '165.0 cm', 'Weight': '52.0 kg'}
460      {'Height': '66.0 cm', 'Weight': '17.0 kg'}
461     {'Height': '170.0 cm', 'Weight': '57.0 kg'}
462     {'Height': '185.0 cm', 'Weight': '81.0 kg'}
Name: Measurements, Length: 463, dtype: object

In [10]:
## examining a single value from the "Measurements" col
meas = super_info_df.loc[0,"Measurements"]

print(type(meas))
meas

<class 'str'>

"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"

In [11]:
## use .str.replace to replace all single quotes
super_info_df['Measurements'] = super_info_df['Measurements'].str.replace("'",'"')

## Apply the json.loads to the full column
super_info_df['Measurements'] = super_info_df['Measurements'].apply(json.loads)
super_info_df['Measurements'].head()

0    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
1     {'Height': '191.0 cm', 'Weight': '65.0 kg'}
2     {'Height': '185.0 cm', 'Weight': '90.0 kg'}
3    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
4    {'Height': '193.0 cm', 'Weight': '122.0 kg'}
Name: Measurements, dtype: object

In [12]:
## examining a single value from the "Measurements" col
meas = super_info_df.loc[0,"Measurements"]

print(type(meas))
meas

<class 'dict'>

{'Height': '203.0 cm', 'Weight': '441.0 kg'}

In [13]:
h_w = super_info_df['Measurements'].apply(pd.Series)
h_w

       Height    Weight
0    203.0 cm  441.0 kg
1    191.0 cm   65.0 kg
2    185.0 cm   90.0 kg
3    203.0 cm  441.0 kg
4    193.0 cm  122.0 kg
..        ...       ...
458  183.0 cm   83.0 kg
459  165.0 cm   52.0 kg
460   66.0 cm   17.0 kg
461  170.0 cm   57.0 kg
462  185.0 cm   81.0 kg

[463 rows x 2 columns]

In [14]:
# concat long_lat with original dataframe
super_info_df = pd.concat((super_info_df, h_w), axis = 1)
super_info_df.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics,203.0 cm,441.0 kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics,191.0 cm,65.0 kg

In [15]:
## drop the original column 
super_info_df = super_info_df.drop(columns='Measurements')

In [16]:
super_info_df.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0 cm,441.0 kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0 cm,65.0 kg

In [17]:
#replacing all " cm" and " kg" in Height and Weight columns.
super_info_df['Height'] = super_info_df['Height'].str.replace(" cm","")
super_info_df['Weight'] = super_info_df['Weight'].str.replace(" kg","")

In [18]:
super_info_df.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0

In [19]:
super_powers_df.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [20]:
super_powers_df["Powers"]

0             Agility,Super Strength,Stamina,Super Speed
1      Accelerated Healing,Durability,Longevity,Super...
2      Agility,Accelerated Healing,Cold Resistance,Du...
3                                     Lantern Power Ring
4      Accelerated Healing,Intelligence,Super Strengt...
                             ...
662                   Flight,Energy Blasts,Size Changing
663    Cold Resistance,Durability,Longevity,Super Str...
664    Agility,Stealth,Danger Sense,Marksmanship,Weap...
665    Cryokinesis,Telepathy,Magic,Fire Control,Proba...
666    Super Speed,Intangibility,Time Travel,Time Man...
Name: Powers, Length: 667, dtype: object

In [21]:
## examining a single value from the "Powers" col
sp = super_powers_df.loc[0,"Powers"]

print(type(sp))
sp

<class 'str'>

'Agility,Super Strength,Stamina,Super Speed'

In [22]:
super_powers_df['Powers'] = super_powers_df['Powers'].str.split(",")

In [23]:
super_powers_df

          hero_names                                             Powers
0            3-D Man    [Agility, Super Strength, Stamina, Super Speed]
1             A-Bomb  [Accelerated Healing, Durability, Longevity, S...
2         Abe Sapien  [Agility, Accelerated Healing, Cold Resistance...
3           Abin Sur                               [Lantern Power Ring]
4        Abomination  [Accelerated Healing, Intelligence, Super Stre...
..               ...                                                ...
662  Yellowjacket II             [Flight, Energy Blasts, Size Changing]
663             Ymir  [Cold Resistance, Durability, Longevity, Super...
664             Yoda  [Agility, Stealth, Danger Sense, Marksmanship,...
665          Zatanna  [Cryokinesis, Telepathy, Magic, Fire Control, ...
666             Zoom  [Super Speed, Intangibility, Time Travel, Time...

[667 rows x 2 columns]

In [24]:
## exploding the column of lists
exploded = super_powers_df.explode('Powers')

In [25]:
exploded

    hero_names               Powers
0      3-D Man              Agility
0      3-D Man       Super Strength
0      3-D Man              Stamina
0      3-D Man          Super Speed
1       A-Bomb  Accelerated Healing
..         ...                  ...
665    Zatanna      Weather Control
666       Zoom          Super Speed
666       Zoom        Intangibility
666       Zoom          Time Travel
666       Zoom    Time Manipulation

[5874 rows x 2 columns]

In [26]:
cols_to_make = exploded['Powers'].dropna().unique()

In [27]:
#for col in cols_to_make:
#    exploded[col] = exploded['Powers'].str.contains(col)
#exploded.head()

for col in cols_to_make:
    super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
super_powers_df.head()

C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)
C:\Users\Rashad\AppData\Local\Temp\ipykernel_9980\2911754120.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super_powers_df[col] = super_powers_df['Powers'].str.contains(col)

,hero_names,Powers,Agility,Super Strength,Stamina,Super Speed,Accelerated Healing,Durability,Longevity,Camouflage,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
0,3-D Man,"[Agility, Super Strength, Stamina, Super Speed]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A-Bomb,"[Accelerated Healing, Durability, Longevity, S...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abe Sapien,"[Agility, Accelerated Healing, Cold Resistance...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abin Sur,[Lantern Power Ring],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Abomination,"[Accelerated Healing, Intelligence, Super Stre...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
ohe_super_powers_df = exploded
ohe_super_powers_df

    hero_names               Powers
0      3-D Man              Agility
0      3-D Man       Super Strength
0      3-D Man              Stamina
0      3-D Man          Super Speed
1       A-Bomb  Accelerated Healing
..         ...                  ...
665    Zatanna      Weather Control
666       Zoom          Super Speed
666       Zoom        Intangibility
666       Zoom          Time Travel
666       Zoom    Time Manipulation

[5874 rows x 2 columns]

In [29]:
super_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      463 non-null    object
 1   Race        463 non-null    object
 2   Alignment   463 non-null    object
 3   Hair color  463 non-null    object
 4   Eye color   463 non-null    object
 5   Skin color  463 non-null    object
 6   Hero        463 non-null    object
 7   Publisher   463 non-null    object
 8   Height      463 non-null    object
 9   Weight      463 non-null    object
dtypes: object(10)
memory usage: 36.3+ KB

In [30]:
super_info_df[['Height','Weight']] = super_info_df[['Height','Weight']].astype('float', copy=None, errors='raise')
super_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      463 non-null    object
 1   Race        463 non-null    object
 2   Alignment   463 non-null    object
 3   Hair color  463 non-null    object
 4   Eye color   463 non-null    object
 5   Skin color  463 non-null    object
 6   Hero        463 non-null    object
 7   Publisher   463 non-null    object
 8   Height      463 non-null    float64
 9   Weight      463 non-null    float64
dtypes: float64(2), object(8)
memory usage: 36.3+ KB

In [31]:
super_info_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0,90.0
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0,441.0
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0,122.0

In [32]:
ohe_super_powers_df.head()

  hero_names               Powers
0    3-D Man              Agility
0    3-D Man       Super Strength
0    3-D Man              Stamina
0    3-D Man          Super Speed
1     A-Bomb  Accelerated Healing

# Combining\Merging dataframes into a single dataframe.

In [33]:
super_info_df.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0

In [34]:
ohe_super_powers_df.head(2)

  hero_names          Powers
0    3-D Man         Agility
0    3-D Man  Super Strength

In [35]:
super_info_df.shape

(463, 10)

In [36]:
super_powers_df.shape

(667, 169)

In [37]:
new_ohe_super_powers_df = ohe_super_powers_df.rename(columns={"hero_names":"Hero"})
new_ohe_super_powers_df.head(2)

      Hero          Powers
0  3-D Man         Agility
0  3-D Man  Super Strength

In [38]:
MERGED_DF= super_info_df.merge(new_ohe_super_powers_df, how='inner', on=["Hero"])
MERGED_DF

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height,Weight,Powers
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0,Accelerated Healing
1,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0,Durability
2,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0,Longevity
3,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0,Super Strength
4,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0,Stamina
...,...,...,...,...,...,...,...,...,...,...,...
4461,Female,Human,good,Black,blue,Unknown,Zatanna,DC Comics,170.0,57.0,Weather Control
4462,Male,Unknown,bad,Brown,red,Unknown,Zoom,DC Comics,185.0,81.0,Super Speed
4463,Male,Unknown,bad,Brown,red,Unknown,Zoom,DC Comics,185.0,81.0,Intangibility
4464,Male,Unknown,bad,Brown,red,Unknown,Zoom,DC Comics,185.0,81.0,Time Travel
4465,Male,Unknown,bad,Brown,red,Unknown,Zoom,DC Comics,185.0,81.0,Time Manipulation

# 1. Compare the average weight of super heros who have Super Speed to those who do not.

In [42]:
ohe_super_powers_df['Super Speed']

KeyError: 'Super Speed'

In [39]:
super_speed_df = ohe_super_powers_df[ohe_super_powers_df['Super Speed'] == True]

KeyError: 'Super Speed'

In [ ]:
super_speed_df

In [ ]:
super_speed_df = super_speed_df.rename(columns={"hero_names":"Hero"})

In [ ]:
super_speed_df

In [ ]:
super_info_df.head()

In [ ]:
HERO_W_SS_MERGED = super_speed_df.merge(super_info_df, how='inner', on=["Hero"])
HERO_W_SS_MERGED

In [ ]:
#Finding those Super Heros who don't have Super Speed.

# filtered ohe_super_speed_df to those without Super Speed and saved to new df
no_super_speed_df = ohe_super_powers_df[ohe_super_powers_df['Super Speed'] == False]

#change the name of the column hero_name to Hero so dataframes can be merged and save\replaced same df
no_super_speed_df = no_super_speed_df.rename(columns={"hero_names":"Hero"})

#Inner Merged no_super_speed_df to super_info_df on Hero column and saved to new df
HERO_NO_SS_MERGED = no_super_speed_df.merge(super_info_df, how='inner', on=["Hero"])

In [ ]:
print(f"Average weight of Super Heros with Super Speed is:  {HERO_W_SS_MERGED['Weight'].mean().round(3)}")
print(f"Average weight of Super Heros without Super Speed is:  {HERO_NO_SS_MERGED['Weight'].mean().round(3)}")

In [41]:
MERGED_DF.groupby('Super Speed')['Weight'].mean()

KeyError: 'Super Speed'

# 2. What is the average height of heroes for each publisher?

In [ ]:
super_info_df.head(3)

In [ ]:
super_info_df.groupby('Publisher').Height.mean()